import "~/styles/globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import Header from "~/components/Header";
import Offer from "~/components/Offer";

export const metadata: Metadata = {
  title: "Ecommerce",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Header />
        <Offer />
        <ToastContainer />
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
